/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type Validation = {
  min?: number
  max?: number
  regex?: string
}

export type SeanceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'seance'
}

export type RedirectLedgerEntry = {
  _id: string
  _type: 'redirectLedgerEntry'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seance?: SeanceReference
  from?: string
  to?: string
  status?: 'mapped' | 'unmapped' | 'dropped'
}

export type QuestionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'question'
}

export type Task = {
  _id: string
  _type: 'task'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seance?: SeanceReference
  page?: string
  mode?: 'auto' | 'human'
  action?:
    | 'rewrite-placeholder'
    | 'generate-alt'
    | 'generate-meta'
    | 'fix-contact'
    | 'normalise-headings'
    | 'map-block'
    | 'verify-testimonial'
    | 'supply-asset'
    | 'custom'
  why?: string
  agentAction?: {
    kind?: 'generate' | 'transform' | 'patch' | 'prompt'
    instruction?: string
    targetPaths?: Array<string>
  }
  status?: 'todo' | 'casting' | 'done' | 'failed' | 'skipped'
  fromQuestion?: QuestionReference
  result?: string
}

export type ExhumedPageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'exhumedPage'
}

export type Question = {
  _id: string
  _type: 'question'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seance?: SeanceReference
  kind?: 'contradiction' | 'authenticity' | 'keep-or-kill' | 'mapping' | 'missing-info'
  prompt?: string
  evidence?: Array<{
    page?: ExhumedPageReference
    quote?: string
    url?: string
    _type: 'evidenceItem'
    _key: string
  }>
  options?: Array<string>
  answer?: string
  answeredBy?: string
  answeredAt?: string
  required?: boolean
  source?: 'claude' | 'knowledgeBase'
  spawnsTasks?: boolean
}

export type ProposedField = {
  _type: 'proposedField'
  name?: string
  type?:
    | 'string'
    | 'text'
    | 'number'
    | 'boolean'
    | 'date'
    | 'datetime'
    | 'url'
    | 'slug'
    | 'image'
    | 'file'
    | 'array'
    | 'object'
    | 'reference'
    | 'portableText'
  of?: Array<string>
  to?: Array<string>
  required?: boolean
  validation?: Validation
  description?: string
  evidenceCount?: number
}

export type ProposedType = {
  _type: 'proposedType'
  name?: string
  title?: string
  kind?: 'document' | 'object' | 'singleton'
  bonesMatch?: string
  fields?: Array<
    {
      _key: string
    } & ProposedField
  >
  rationale?: string
  evidence?: Array<{
    page?: ExhumedPageReference
    excerpt?: string
    _type: 'typeEvidence'
    _key: string
  }>
  confidence?: number
  decision?: 'keep' | 'merge' | 'drop'
  mergeInto?: string
}

export type SchemaProposal = {
  _id: string
  _type: 'schemaProposal'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seance?: SeanceReference
  version?: number
  types?: Array<
    {
      _key: string
    } & ProposedType
  >
  acceptedAt?: string
}

export type ExhumedPage = {
  _id: string
  _type: 'exhumedPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  seance?: SeanceReference
  url?: string
  path?: string
  httpStatus?: number
  title?: string
  meta?: {
    description?: string
    ogImage?: string
    canonical?: string
  }
  headings?: Array<string>
  sections?: Array<{
    kind?: string
    html?: string
    text?: string
    _type: 'exhumedSection'
    _key: string
  }>
  images?: Array<{
    src?: string
    alt?: string
    width?: number
    height?: number
    _type: 'exhumedImage'
    _key: string
  }>
  links?: Array<string>
  detectedEntities?: {
    phones?: Array<string>
    emails?: Array<string>
    addresses?: Array<string>
    prices?: Array<string>
  }
  contentHash?: string
  html?: string
}

export type Seance = {
  _id: string
  _type: 'seance'
  _createdAt: string
  _updatedAt: string
  _rev: string
  url?: string
  slug?: Slug
  platform?: 'wordpress' | 'durable' | 'wix' | 'squarespace' | 'webflow' | 'static' | 'unknown'
  platformConfidence?: number
  targetMode?: 'dataset' | 'project'
  targetDataset?: string
  targetProjectId?: string
  visibility?: 'private' | 'public'
  pageCap?: number
  brand?: {
    colors?: Array<string>
    fonts?: Array<string>
    logo?: string
  }
  stats?: {
    pages?: number
    images?: number
    words?: number
    links?: number
  }
  exhumeProgress?: number
  status?: 'alive' | 'haunted' | 'risen' | 'entombed'
  entombedReason?: string
  startedBy?: string
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Validation
  | SeanceReference
  | RedirectLedgerEntry
  | QuestionReference
  | Task
  | ExhumedPageReference
  | Question
  | ProposedField
  | ProposedType
  | SchemaProposal
  | ExhumedPage
  | Seance
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
